# Worksheet 02

Name: Zhi Zheng

UID: U92700642

### Topics

- Effective Programming

### Effective Programming

a) What is a drawback of the top down approach?

Less chance for creativity: 

b) What is a drawback of the bottom up approach?

Hard to manage the team: 

c) What are 3 things you can do to have a better debugging experience?

1. Read the error
2. Look online for some help
3. Take breaks

d) (Optional) Follow along with the live coding. You can write your code here:

In [2]:
class Board():
    
    def __init__(self):
        self.queen = "Q"
        self.blank = "-"
        self.board = [["-" for _ in range(8)] for _ in range(8)]
        
    def __repr__(self):
        return "\n".join([" ".join(x) for x in self.board])
    
    def is_queen(self, row, col):
        return self.board[row][col] == self.queen
    
    def is_on_board(self, row, col):
        if row < 0 or row > 7:
            return False
        if col < 0 or col > 7:
            return False
        return True
    
    def is_valid_row(self, row):
        for i in range(8):
            if self.is_queen(row, i):
                return False
        return True
        
    def is_valid_col(self, col):
        for i in range(8):
            if self.is_queen(i, col):
                return False
        return True
    
    def is_valid_diag(self, row, col):
        for i in range(1, 8):
            if self.is_on_board(row-i, col-i) and self.is_queen(row-i, col-i):
                return False
            if self.is_on_board(row+i, col-i) and self.is_queen(row+i, col-i):
                return False
            if self.is_on_board(row-i, col+i) and self.is_queen(row-i, col+i):
                return False
            if self.is_on_board(row+i, col+i) and self.is_queen(row+i, col+i):
                return False
        return True
    
    def is_valid_move(self, row, col):
#         if self.num_queens() > 8:
#             return False
        if not self.is_on_board(row, col):
            return False
        if not self.is_valid_row(row):
            return False
        if not self.is_valid_col(col):
            return False
        if not self.is_valid_diag(row, col):
            return False
        return True
        
    def set_queen_at(self, row, col):
        self.board[row][col] = self.queen
        
    def find_queen_on(self, row):
        for col in range(8):
            if self.is_queen(row, col):
                return col
        raise ValueError("programmer error")
        
    def unset_queen_on(self, row):
        self.board[row] = ["-" for _ in range(8)]
    
    def search(self):
        row = 0
        col = 0
        while row < 8:
            if self.is_valid_move(row, col):
                self.set_queen_at(row, col)
                row += 1
                col = 0
            else:
                col += 1
                if col >= 8:
                    col = self.find_queen_on(row - 1) + 1
                    self.unset_queen_on(row - 1)
                    row -= 1
        print(self)
                    
board = Board()
board
print()
board.search()


Q - - - - - - -
- - - - Q - - -
- - - - - - - Q
- - - - - Q - -
- - Q - - - - -
- - - - - - Q -
- Q - - - - - -
- - - Q - - - -


In [1]:
import numpy as np
x = [[1, 2, 3], [1, 0, 0], [0, 1, 0], [0, 0, 1]]
y = [1.1, 1.9, 3.1]
k = [[3, 3, 3, 3], [3, 3, 3, 3], [3, 3, 3, 3], [3, 3, 3, 3]]
p = 100
print(np.dot(np.dot(np.linalg.inv((np.dot(x, np.transpose(x)) + np.dot(k, p))), x), np.transpose(y)))
print(np.dot(x, np.transpose(x)) + np.dot(k, p))
print(np.linalg.inv((np.dot(x, np.transpose(x)) + np.dot(k, p))))
print(x * np.transpose(y))
print(np.dot(np.linalg.inv((np.dot(x, np.transpose(x)) + np.dot(k, p))), (x * np.transpose(y))))

[ 1.22 -0.12 -0.54 -0.56]
[[314 301 302 303]
 [301 301 300 300]
 [302 300 301 300]
 [303 300 300 301]]
[[ 0.12013333  0.07986667 -0.04026667 -0.1604    ]
 [ 0.07986667  0.72013333 -0.35973333 -0.4396    ]
 [-0.04026667 -0.35973333  0.68053333 -0.2792    ]
 [-0.1604     -0.4396     -0.2792      0.8812    ]]
[[1.1 3.8 9.3]
 [1.1 0.  0. ]
 [0.  1.9 0. ]
 [0.  0.  3.1]]
[[ 0.22  0.38  0.62]
 [ 0.88 -0.38 -0.62]
 [-0.44  1.14 -1.24]
 [-0.66 -1.14  1.24]]
